import Head from "next/head"

const SiteHead = () =>{
    return(
    <Head>
    <title>Tsuzukuru | はじめて続く、作るサイクル</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    </Head>
    )
}

export default SiteHead